WITH expected_columns(table_name, column_name) AS (
    VALUES
        ('administradores', 'id'),
        ('administradores', 'login'),
        ('administradores', 'senha_hash'),
        ('administradores', 'email'),
        ('administradores', 'cnpj_cpf'),
        ('administradores', 'nome_completo'),
        ('administradores', 'ativo'),
        ('administradores', 'criado_em'),
        ('gerentes', 'id'),
        ('gerentes', 'admin_id'),
        ('gerentes', 'login'),
        ('gerentes', 'senha_hash'),
        ('gerentes', 'email'),
        ('gerentes', 'cnpj_cpf'),
        ('gerentes', 'nome_empresa'),
        ('gerentes', 'nome_completo'),
        ('gerentes', 'ativo'),
        ('gerentes', 'criado_em'),
        ('usuarios_finais', 'id'),
        ('usuarios_finais', 'gerente_id'),
        ('usuarios_finais', 'admin_id'),
        ('usuarios_finais', 'login'),
        ('usuarios_finais', 'senha_hash'),
        ('usuarios_finais', 'email'),
        ('usuarios_finais', 'cnpj_cpf'),
        ('usuarios_finais', 'nome'),
        ('usuarios_finais', 'nome_completo'),
        ('usuarios_finais', 'perfil'),
        ('usuarios_finais', 'ativo'),
        ('usuarios_finais', 'criado_em'),
        ('contas_recorrentes', 'id'),
        ('contas_recorrentes', 'admin_id'),
        ('contas_recorrentes', 'gerente_id'),
        ('contas_recorrentes', 'cnpj_cpf_gerente'),
        ('contas_recorrentes', 'usuario_id'),
        ('contas_recorrentes', 'login_usuario'),
        ('contas_recorrentes', 'cnpj_cpf_usuario'),
        ('contas_recorrentes', 'valor_fixo'),
        ('contas_recorrentes', 'dia_vencimento'),
        ('contas_recorrentes', 'descricao'),
        ('contas_recorrentes', 'ativa'),
        ('contas_recorrentes', 'criado_em'),
        ('contas_receber', 'id'),
        ('contas_receber', 'usuario_id'),
        ('contas_receber', 'cnpj_cpf'),
        ('contas_receber', 'login'),
        ('contas_receber', 'valor_devido'),
        ('contas_receber', 'data_vencimento'),
        ('contas_receber', 'status'),
        ('contas_receber', 'cfop'),
        ('contas_receber', 'criado_em'),
        ('contas_receber', 'recorrente_id'),
        ('logs_auditoria', 'id'),
        ('logs_auditoria', 'usuario_id'),
        ('logs_auditoria', 'tipo_usuario'),
        ('logs_auditoria', 'cnpj_cpf'),
        ('logs_auditoria', 'acao'),
        ('logs_auditoria', 'dados_novos'),
        ('logs_auditoria', 'dados_antigos'),
        ('logs_auditoria', 'data_hora'),
        ('aliquotas_padrao', 'id'),
        ('aliquotas_padrao', 'cfop'),
        ('aliquotas_padrao', 'descricao'),
        ('aliquotas_padrao', 'aliquota_icms_esperada'),
        ('aliquotas_padrao', 'aliquota_pis_esperada'),
        ('aliquotas_padrao', 'aliquota_cofins_esperada'),
        ('aliquotas_padrao', 'aliquota_ipi_esperada'),
        ('aliquotas_padrao', 'regime'),
        ('aliquotas_padrao', 'anexo'),
        ('aliquotas_padrao', 'criado_em'),
        ('tickets_suporte', 'id'),
        ('tickets_suporte', 'usuario_id'),
        ('tickets_suporte', 'usuario_login'),
        ('tickets_suporte', 'usuario_email'),
        ('tickets_suporte', 'tipo_problema'),
        ('tickets_suporte', 'assunto'),
        ('tickets_suporte', 'descricao'),
        ('tickets_suporte', 'prioridade'),
        ('tickets_suporte', 'status'),
        ('tickets_suporte', 'data_criacao'),
        ('tickets_suporte', 'data_resposta'),
        ('tickets_suporte', 'resposta_admin'),
        ('tickets_suporte', 'admin_id'),
        ('ticket_mensagens', 'id'),
        ('ticket_mensagens', 'ticket_id'),
        ('ticket_mensagens', 'autor_tipo'),
        ('ticket_mensagens', 'autor_id'),
        ('ticket_mensagens', 'mensagem'),
        ('ticket_mensagens', 'criado_em')
)
SELECT expected_columns.table_name, expected_columns.column_name
FROM expected_columns
LEFT JOIN information_schema.columns
    ON information_schema.columns.table_schema = 'public'
    AND information_schema.columns.table_name = expected_columns.table_name
    AND information_schema.columns.column_name = expected_columns.column_name
WHERE information_schema.columns.column_name IS NULL
ORDER BY expected_columns.table_name, expected_columns.column_name;
